WebPortal/SLEWebPortal/Models/Prospect.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SLEWebPortal.Models
{
    public class Prospect
    {
        public string ProspectNo
        {
            set;
            get;
        }

        public string ProspectName
        {
            get;
            set;
        }

        public string AddressLine1
        {
            get;
            set;
        }
        public string AddressLine2
        {
            get;
            set;
        }
        public string AddressLine3
        {
            get;
            set;
        }
        public string AddressLine4
        {
            get;
            set;
        }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string ZipCode { get; set; }

        public string AreaCode1 { get; set; }
        public string Phone1 { get; set; }
        public string AreaCode2 { get; set; }
        public string Phone2 { get; set; }
        public string AreaCode3 { get; set; }
        public string Phone3 { get; set; }
        public string AreaCode4 { get; set; }
        public string Phone4 { get; set; }
        public string EmailID1 { get; set; }       
        public string EmailID2 { get; set; }
        public string EmailID3 { get; set; }
    }
}

WebPortal/SLEWebPortal/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using log4net;
using SLEWebPortal.Managers;
using SLEWebPortal.Models;
namespace SLEWebPortal.Controllers
{
    [Authorize]
    [SessionExpire]
    public class DashboardController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: Dashboard
        public ActionResult Index()
        {
            Models.DashboardModels dashboardModel = new Models.DashboardModels();
            try
            {
                logger.Info("DashboardController Index");
           
            dashboardModel.Orders = new Managers.OrderManager().GetOrderList();
            dashboardModel.RecentOrders = new Managers.OrderManager().GetRecentOrders();
            dashboardModel.VoidOrders = new Managers.OrderManager().GetVoidOrders();
            dashboardModel.VoidOrdersForToday = new Managers.OrderManager().GetVoidOrdersForToday("");
            dashboardModel.CreditOrders = new OrderManager().GetCreditOrderList();
            dashboardModel.CreditOrdersForToday = new OrderManager().GetCreditOrdersForToday("");
                dashboardModel.TotalOrders = dashboardModel.Orders.Count();
                dashboardModel.TotalOrdersForToday = dashboardModel.RecentOrders.Count(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));
                dashboardModel.TotalVoidOrders = dashboardModel.VoidOrders.Count();
                dashboardModel.TotalVoidOrdersForToday = dashboardModel.VoidOrdersForToday.Count(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));
                dashboardModel.TotalCreditOrders = dashboardModel.CreditOrders.Count<Order>();
                dashboardModel.TotalCreditOrdersForToday = dashboardModel.CreditOrdersForToday.Count((Order item) => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));

                dashboardModel.TotalCustomers = Convert.ToInt32(new Managers.CustomerManager().GetAllCustomersCount());
                dashboardModel.TotalProspects = Convert.ToInt32(new Managers.ProspectManager().GetAllProspectsCount());
                dashboardModel.graphorders = new Managers.OrderManager().GetTodayCoffee();
           //     today();
                dashboardModel.RecentOrders = dashboardModel.RecentOrders.Where(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy")).ToList();
                dashboardModel.TotalPaymentAmountForToday=new Managers.OrderManager().GetTotalPayment();
                dashboardModel.TotalPaymentAmountForToday=Convert.ToDouble(String.Format("{0:0.00}", dashboardModel.TotalPaymentAmountForToday));
              //  dashboardModel.totalcoffee = new Managers.OrderManager().GetTotalCoffee();


            }
            catch (Exception ex)
            {
               // logger.Error("Error in CustomerController Index" + ex.Message);
                throw ex;
            }
            return View(dashboardModel);
        }



        public List<Models.Order> SetOrderStates(List<Models.Order> Orders)
        {
            foreach (Models.Order item in Orders)
            {
                if (item.OrderState.ToLower().Contains("hold") )
                {
                    item.OrderSubState = "../content/images/Hold.png";
                }
                else if (item.OrderState.ToLower().Contains("void"))
                {
                    item.OrderSubState = "../content/images/Void.png";
           //         item.OrderState = "Cancelled";
                }                

                //if (item.OrderState == OrderStatus.OrderTemplate.ToString())
                //{
                //    item.OrderState = "In Progress";
                //}
                //else if (item.OrderState == OrderStatus.OrderEntry.ToString())
                //{
                //    item.OrderState = "In Progress";
                //}
                //else if (item.OrderState == OrderStatus.OrderPreview.ToString())
                //{
                //    item.OrderState = "In Progress";
                //}
                //else if (item.OrderState == OrderStatus.OrderAcceptance.ToString())
                //{
                //    item.OrderState = "In Progress";
                //}
                //else if (item.OrderState == OrderStatus.PickOrder.ToString())
                //{
                //    item.OrderState = "In Progress";
                //}
                //else if (item.OrderState == OrderStatus.CashCollection.ToString())
                //{
                //    item.OrderState = "In Progress";
                //}
                if (item.OrderState.Trim() == OrderStatus.OrderDelivered.ToString())
                {
                    item.OrderState = "Delivered";
                }
                else if (item.OrderState.ToLower().Contains("void"))
                {
                    item.OrderState = "Cancelled";
                }
                else {
                    item.OrderState = "In Progress";
                }
              

                /*else
                {
                    item.OrderState = "Delivered";
                }*/
            }
            return Orders;
        }
        public ActionResult OrderList()
        {
            try
            {
                logger.Info("DashboardController OrderList");
                Models.DashboardModels dashboardModel = new Models.DashboardModels();
                List<Models.Order> Orders = new Managers.OrderManager().GetOrderList();
                dashboardModel.Orders = SetOrderStates(Orders);
                return View("OrderList", dashboardModel);
            }
            catch (Exception ex)
            {
                logger.Error("Error in DashboardController OrderList" + ex.Message);
                throw ex;
            }
        }

        public ActionResult yearly()
        {
            Models.DashboardModels dashboardModel = new Models.DashboardModels();
            try
            {
                logger.Info("DashboardController yearly");
                
                dashboardModel.Orders = new Managers.OrderManager().GetOrderList();
     //           dashboardModel.RecentOrders = new Managers.OrderManager().GetRecentOrders();
     //           dashboardModel.VoidOrders = new Managers.OrderManager().GetVoidOrders();
     //           dashboardModel.VoidOrdersForToday = new Managers.OrderManager().GetVoidOrdersForToday("");

     //           dashboardModel.TotalOrders = dashboardModel.Orders.Count();
     //           dashboardModel.TotalOrdersForToday = dashboardModel.RecentOrders.Count(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));
     //           dashboardModel.TotalVoidOrders = dashboardModel.VoidOrders.Count();
     //           dashboardModel.TotalVoidOrdersForToday = dashboardModel.VoidOrdersForToday.Count(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));


    //            dashboardModel.TotalCustomers = new Managers.CustomerManager().GetAllCustomers().Count();
                dashboardModel.graphorders = new Managers.OrderManager().GetYearlyCoffee();
     //           dashboardModel.TotalPaymentAmountForToday = dashboardModel.Orders.Sum(item => Convert.ToInt32(item.OrderTotal));
              //  dashboardModel.graphorders = new Managers.OrderManager().GetYearlyCoffee();
                
            }
            catch (Exception ex)
            {
             //   logger.Error("Error in DashboardController OrderList" + ex.Message);
                //throw ex;
            }
        //    return View("Index",dashboardModel);
            return PartialView("_graph", dashboardModel);
        }
       
        public ActionResult monthly()
        {
            Models.DashboardModels dashboardModel = new Models.DashboardModels();
            try
            {
                logger.Info("DashboardController yearly");

                dashboardModel.Orders = new Managers.OrderManager().GetOrderList();
 //               dashboardModel.RecentOrders = new Managers.OrderManager().GetRecentOrders();
  //              dashboardModel.VoidOrders = new Managers.OrderManager().GetVoidOrders();
  //              dashboardModel.VoidOrdersForToday = new Managers.OrderManager().GetVoidOrdersForToday("");

  //              dashboardModel.TotalOrders = dashboardModel.Orders.Count();
  //              dashboardModel.TotalOrdersForToday = dashboardModel.RecentOrders.Count(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));
  //              dashboardModel.TotalVoidOrders = dashboardModel.VoidOrders.Count();
  //              dashboardModel.TotalVoidOrdersForToday = dashboardModel.VoidOrdersForToday.Count(item => Convert.ToDateTime(item.OrderDate).ToString("dd/MMM/yyyy") == DateTime.Now.ToString("dd/MMM/yyyy"));


  //              dashboardModel.TotalCustomers = new Managers.CustomerManager().GetAllCustomers().Count();
                dashboardModel.graphorders = new Managers.OrderManager().GetMonthlyCoffee();
           //     dashboardModel.TotalPaymentAmountForToday = dashboardModel.Orders.Sum(item => Convert.ToInt32(item.OrderTotal));
                //  dashboardModel.graphorders = new Managers.OrderManager().GetYearlyCoffee();

            }
            catch (Exception ex)
            {
                //   logger.Error("Error in DashboardController OrderList" + ex.Message);
                //throw ex;
            }
         //  return View("Index", dashboardModel);
            return PartialView("_graph", dashboardModel);
        }

WebPortal/SLEWebPortal/Views/Dashboard/CreditOrderList.cshtml
@{
    ViewBag.Title = "Credit Orders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SLEWebPortal.Models.DashboardModels

@*<div class="row wrapper border-bottom white-bg page-heading">

        <div class="col-lg-2">

        </div>
    </div>*@
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title order-list-title col-md-6">
                    <h5>List of Credit Orders</h5>
                </div>
                <div class="ibox-corner-data ibox-title col-md-6">
                    <h5>Total Orders : @Model.CreditOrders.Count</h5>
                </div>
                <div class="ibox-content order-list-box-container">
                    <div class="order-list-container col-md-12">
                        @if (@Model.CreditOrders.Count == 0)
                        {
                            <tr>
                                <td colspan="5" class="responseMsg">No data available in table</td>
                            </tr>
                        }
                        @for (int i = 1; i <= @Model.CreditOrders.Count; i++)
                        {
                            <div class="order-item-container col-md-12">
                                <div class="order-item-header col-md-4" style="width:27%;">
                                    <span class="orderIdHeader">
                                        <span class="header">
                                            Order No.:
                                            <span>@Model.CreditOrders.ElementAt(i - 1).OrderID</span>
                                        </span>
                                        <span class="order-header-date">@Convert.ToDateTime(Model.CreditOrders.ElementAt(i - 1).OrderDate).ToString("MM/dd/yyyy")</span>
                                    </span>
                                    <span class="orderIdHeader">
                                        <span class="order-id-value">@Model.CreditOrders.ElementAt(i - 1).CustomerNo</span>
                                        <span class="order-id-value" style="font-weight:normal;">,@Model.CreditOrders.ElementAt(i - 1).CustomerName</span>
                                        <span class="order-header-title"></span>
                                    </span>

                                </div>
                                <div class="order-item-desc col-md-2" style="width:15%;">
                                    <span class="order-id-value">Total Allied:  $ @Model.CreditOrders.ElementAt(i - 1).TotalAllied </span>

                                </div>
                                <div class="order-item-desc col-md-2" style="width:15%;">
                                    <span class="order-id-value"> Total Coffee: $ @Model.CreditOrders.ElementAt(i - 1).TotalCoffee </span>
                                </div>
                                <div class="order-item-desc col-md-2" style="width:20%;">
                                    <span class="order-id-value amount-value font-bold"> Total Amount: $ @Model.CreditOrders.ElementAt(i - 1).OrderTotal </span>
                                </div>
                                <div class="order-item-desc col-md-2" style="width:10%;">
                                    <span class="order-id-value">@Model.CreditOrders.ElementAt(i - 1).OrderState </span>
                                </div>
                                <div class="order-item-desc col-md-1" style="width:10%; ">
                                    <img src="@Model.CreditOrders.ElementAt(i - 1).OrderSubState" onerror="this.style.display='none'" />
                                </div>
                                <div class="order-item-desc col-md-1" style=" padding:0px 0px; width:0.3333333%;">
                                    <i class="fa fa-angle-down btn-detail order-detail-click font-bold" style="font-weight:bold; font-size:14px; color:#646464; margin-left:5px; margin-top:15px; cursor:pointer" data-target=@Model.CreditOrders.ElementAt(i - 1).OrderID></i>
                                </div>
                                <div id="accordion" class="order-detail-container col-md-12" data-element=@Model.CreditOrders.ElementAt(i - 1).OrderID>
                                    <div class="order-detail-panel col-md-12">
                                        <div class="order-detail-title" style="font-weight:bold;">List of Items</div>
                                        <div class="order-detail-list col-md-12">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/plugins/flot")
    @Scripts.Render("~/plugins/vectorMap")

    <script type="text/javascript">
        $(document).ready(function () {
            var accordionDiv = $('.order-detail-container').hide();
            var data2 = [
               [gd(2012, 1, 1), 7], [gd(2012, 1, 2), 6], [gd(2012, 1, 3), 4], [gd(2012, 1, 4), 8],
               [gd(2012, 1, 5), 9], [gd(2012, 1, 6), 7], [gd(2012, 1, 7), 5], [gd(2012, 1, 8), 4],
               [gd(2012, 1, 9), 7], [gd(2012, 1, 10), 8], [gd(2012, 1, 11), 9], [gd(2012, 1, 12), 6],
               [gd(2012, 1, 13), 4], [gd(2012, 1, 14), 5], [gd(2012, 1, 15), 11], [gd(2012, 1, 16), 8],
               [gd(2012, 1, 17), 8], [gd(2012, 1, 18), 11], [gd(2012, 1, 19), 11], [gd(2012, 1, 20), 6],
               [gd(2012, 1, 21), 6], [gd(2012, 1, 22), 8], [gd(2012, 1, 23), 11], [gd(2012, 1, 24), 13],
               [gd(2012, 1, 25), 7], [gd(2012, 1, 26), 9], [gd(2012, 1, 27), 9], [gd(2012, 1, 28), 8],
               [gd(2012, 1, 29), 5], [gd(2012, 1, 30), 8], [gd(2012, 1, 31), 25]
            ];

            var data3 = [
                [gd(2012, 1, 1), 800], [gd(2012, 1, 2), 500], [gd(2012, 1, 3), 600], [gd(2012, 1, 4), 700],
                [gd(2012, 1, 5), 500], [gd(2012, 1, 6), 456], [gd(2012, 1, 7), 800], [gd(2012, 1, 8), 589],
                [gd(2012, 1, 9), 467], [gd(2012, 1, 10), 876], [gd(2012, 1, 11), 689], [gd(2012, 1, 12), 700],
                [gd(2012, 1, 13), 500], [gd(2012, 1, 14), 600], [gd(2012, 1, 15), 700], [gd(2012, 1, 16), 786],
                [gd(2012, 1, 17), 345], [gd(2012, 1, 18), 888], [gd(2012, 1, 19), 888], [gd(2012, 1, 20), 888],
                [gd(2012, 1, 21), 987], [gd(2012, 1, 22), 444], [gd(2012, 1, 23), 999], [gd(2012, 1, 24), 567],
                [gd(2012, 1, 25), 786], [gd(2012, 1, 26), 666], [gd(2012, 1, 27), 888], [gd(2012, 1, 28), 900],
                [gd(2012, 1, 29), 178], [gd(2012, 1, 30), 555], [gd(2012, 1, 31), 993]
            ];


            var dataset = [
                {
                    label: "Number of orders",
                    data: data3,
                    color: "#1ab394",
                    bars: {
                        show: true,
                        align: "center",
                        barWidth: 24 * 60 * 60 * 600,
                        lineWidth: 0
                    }

                }, {
                    label: "Payments",
                    data: data2,
                    yaxis: 2,
                    color: "#464f88",
                    lines: {
                        lineWidth: 1,
                        show: true,
                        fill: true,
                        fillColor: {
                            colors: [{
                                opacity: 0.2
                            }, {
                                opacity: 0.2
                            }]
                        }
                    },
                    splines: {
                        show: false,
                        tension: 0.6,
                        lineWidth: 1,
                        fill: 0.1
                    },
                }
            ];


            var options = {
                xaxis: {
                    mode: "time",
                    tickSize: [3, "day"],
                    tickLength: 0,
                    axisLabel: "Date",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: 'Arial',
                    axisLabelPadding: 10,
                    color: "#d5d5d5"
                },
                yaxes: [{
                    position: "left",
                    max: 1070,
                    color: "#d5d5d5",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: 'Arial',
                    axisLabelPadding: 3
                }, {
                    position: "right",
                    clolor: "#d5d5d5",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: ' Arial',
                    axisLabelPadding: 67
                }
                ],
                legend: {
                    noColumns: 1,
                    labelBoxBorderColor: "#000000",
                    position: "nw"
                },
                grid: {
                    hoverable: false,
                    borderWidth: 0
                }
            };

            function gd(year, month, day) {
                return new Date(year, month - 1, day).getTime();
            }

            var previousPoint = null, previousLabel = null;

            var mapData = {
                "US": 298,
                "SA": 200,
                "DE": 220,
                "FR": 540,
                "CN": 120,
                "AU": 760,
                "BR": 550,
                "IN": 200,
                "GB": 120,
            };
            $('.btn-detail').click(function (e) {
                //debugger
                var currentElem = e.currentTarget;
                var dataId = $(currentElem).attr('data-target');
                var currentSelectedBtn = $('[data-element ="' + dataId + '"]').prev().find('.order-detail-click');
                var previousSelectedElement = accordionDiv.not('[data-element ="' + dataId + '"]').prev().find('.order-detail-click');
             //   var accordionDiv = $("tr#accordion").hide();

                $.ajax({
                    // method: 'POST', <-- remove this
                    type: 'POST', // <-- add this
                    url: "@Url.Action("OrderDetails","Dashboard")",
                    data: { orderID: dataId },
                    success: function (data) {
                        //var debugging = false; // or true
                        //if (typeof console == "undefined") var console = { log: function () { } };
                        //else if (!debugging || typeof console.log == "undefined") console.log = function () { };
                        console.log("success");
                        $('[data-element ="' + dataId + '"] .order-detail-panel').find('.order-detail-list').html(data);
                        $('[data-element ="' + dataId + '"] .order-detail-panel').addClass('selected');
                        console.log(data);
                    },
                    error: function (error) {
                        console.log('error');
                    }
                });
                accordionDiv.not('[data-element ="' + dataId + '"]').prev().removeClass('active');
                $('[data-element ="' + dataId + '"]').prev().addClass('active');
                $('[data-element ="' + dataId + '"]').slideToggle("slow");
                if ($(currentSelectedBtn).hasClass('fa-angle-down'))
                    $(currentSelectedBtn).removeClass('fa-angle-down').addClass('fa-angle-up');
                else {
                    $(currentSelectedBtn).removeClass('fa-angle-up').addClass('fa-angle-down');

                }
                if (previousSelectedElement.hasClass('fa-angle-up'))
                    previousSelectedElement.removeClass('fa-angle-up').addClass('fa-angle-down');
                accordionDiv.not('[data-element ="' + dataId + '"]').slideUp("slow");



            });
            $('#world-map').vectorMap({
                map: 'world_mill_en',
                backgroundColor: "transparent",
                regionStyle: {
                    initial: {
                        fill: '#e4e4e4',
                        "fill-opacity": 0.9,
                        stroke: 'none',
                        "stroke-width": 0,
                        "stroke-opacity": 0
                    }
                },

                series: {
                    regions: [{
                        values: mapData,
                        scale: ["#1ab394", "#22d6b1"],
                        normalizeFunction: 'polynomial'
                    }]
                },
            });

        });
    </script>
}

WebPortal/SLEWebPortal/Views/Dashboard/CreditOrdersForToday.cshtml
@{
    ViewBag.Title = "Credit Orders For Today";
}
@model SLEWebPortal.Models.DashboardModels

<h2>New Credit Orders For Today</h2>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Total Orders : @Model.CreditOrders.Count</h5>
                </div>
                <div class="ibox-content">
                    <table class="table table-responsive order-list-table">
                        <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>Customer No</th>
                                <th>Order Date</th>
                                <th>Total Coffee</th>
                                <th>Total Allied</th>
                                <th>Order Total</th>
                                <th>Sales Tax Amount</th>
                                <th>Order State</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (@Model.CreditOrders.Count == 0)
                            {
                                <tr>
                                    <td colspan="5" class="responseMsg">No data available in table</td>
                                </tr>
                            }
                            @for (int i = 1; i <= @Model.CreditOrders.Count; i++)
                            {
                                <tr>
                                    <td>@Model.CreditOrders.ElementAt(i - 1).OrderID</td>
                                    <td>@Model.CreditOrders.ElementAt(i - 1).CustomerNo</td>
                                    <td>@Convert.ToDateTime(Model.CreditOrders.ElementAt(i - 1).OrderDate).ToString("MM/dd/yyyy")</td>
                                    <td>$ @Model.CreditOrders.ElementAt(i - 1).TotalCoffee</td>
                                    <td>$ @Model.CreditOrders.ElementAt(i - 1).TotalAllied</td>
                                    <td>$ @Model.CreditOrders.ElementAt(i - 1).OrderTotal</td>
                                    <td>$ @Model.CreditOrders.ElementAt(i - 1).SalesTaxAmount</td>
                                    <td>@Model.CreditOrders.ElementAt(i - 1).OrderState</td>
                                    <td>
                                        <img src="@Model.CreditOrders.ElementAt(i - 1).OrderSubState" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
@section Scripts {
    @Scripts.Render("~/plugins/flot")
    @Scripts.Render("~/plugins/vectorMap")

    <script>
            $('.btn-detail').click(function (e) {
                debugger
                var currentElem = e.currentTarget;
                var dataId = $(currentElem).attr('data-target');
                var accordionDiv = $("tr#accordion").hide();

                $.ajax({
                    // method: 'POST', <-- remove this
                    type: 'POST', // <-- add this
                    url: "@Url.Action("OrderDetails","Dashboard")",
                    data: { orderID: dataId },
                    success: function (data) {
                        console.log("success");
                        $('[data-element ="' + dataId + '"] .detail-container').html(data);
                        $('tr[data-element ="' + dataId + '"] > td').addClass('selected');
                        console.log(data);
                    },
                    error: function (error) {
                        console.log('error');
                    }
                });
                accordionDiv.not('[data-element ="' + dataId + '"]').prev().removeClass('active');
                $('tr[data-element ="' + dataId + '"]').prev().addClass('active');
                $(currentElem).find('i').removeClass('fa fa-folder-open').addClass('fa fa-folder')
                $('[data-element ="' + dataId + '"]').slideToggle("slow");

                accordionDiv.not('[data-element ="' + dataId + '"]').slideUp("slow");


            });
            $('#world-map').vectorMap({
                map: 'world_mill_en',
                backgroundColor: "transparent",
                regionStyle: {
                    initial: {
                        fill: '#e4e4e4',
                        "fill-opacity": 0.9,
                        stroke: 'none',
                        "stroke-width": 0,
                        "stroke-opacity": 0
                    }
                },

                series: {
                    regions: [{
                        values: mapData,
                        scale: ["#1ab394", "#22d6b1"],
                        normalizeFunction: 'polynomial'
                    }]
                },
            });

        });
    </script>
}

WebPortal/SLEWebPortal/Views/Dashboard/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
    <meta http-equiv="X-UA-Compatible" content="IE=Edge ,IE=10 , IE=EmulateIE9" /> 
    <title>SLE | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/fonts/font-awesome/css")
    @Scripts.Render("~/bundles/jquery")
    <link href="/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/metsiMenu")
    @Scripts.Render("~/plugins/pace")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @RenderSection("scripts", required: false)
</body>
</html>