WebPortal/SLEWebPortal/Controllers/DeliveryDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SLEWebPortal.Models;
using System.Web.Script.Serialization;

namespace SLEWebPortal.Controllers
{
    [SessionExpire]
    public class DeliveryDayController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: DeliveryDay
        public ActionResult Index()
        {
            try
            {
                logger.Info("DeliveryDayController Index");
                SLEWebPortal.Models.DelieveryViewModel model = new Models.DelieveryViewModel();
                model.TotalCodes = new Managers.DayCodeManager().GetAllMessages();
                model.TotalCodesForToday = new Managers.DayCodeManager().GetDayCodeListForToday();
                return View(model);
               
            }
            catch (Exception ex)
            {
                logger.Error("Error in DeliveryDayController Index" + ex.Message);
                throw ex;
            }
        }
        public ActionResult Configuration(DelieveryViewModel mod)
        {
            //int number = (int)TempData["weeks"];
            //if (mod.Stops == 0)
            //{

            //    string[] dayweeks = new Managers.DayCodeManager().GetConfig(mod.DelieveryCode);
            //    TempData["dayweeks"] = "hi";
            //    return View(mod);
                
            //}
            //else
            //{
                return View(mod);

         //   }
           
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AddDayCode(DelieveryViewModel mod)
        {
            try
            {
                logger.Info("DeliveryDayController AddDayCode Parameters: " + mod);
                if (!ModelState.IsValid)
                {
                    SLEWebPortal.Models.DelieveryViewModel model = new Models.DelieveryViewModel();
                    model.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();

                    return View("Index", model);
                }

                var daycode = mod.DelieveryCode;
                var weeks = mod.Weeks;
                var desc = mod.Description;
                
                new Managers.DayCodeManager().AddDayCode(daycode, weeks, desc.Trim());
                //var response = new Response(true, "Day Code Added!");
                //return Json(response);
                SLEWebPortal.Models.DelieveryViewModel model2 = new Models.DelieveryViewModel();
                model2.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();
                model2.TotalCodesForToday = new Managers.DayCodeManager().GetDayCodeListForToday();
                //////model2.TotalDevices = model2.Devices.Count;
                //////model2.ActiveDevices = Convert.ToInt32(model2.Devices.Count(dev => dev.Active == 1));
                TempData["Weeks"] = mod.Weeks;
                TempData["daycode"] = mod.DelieveryCode;
                TempData["desc"] = mod.Description.Trim();
                return View("Index", model2);

            }
            catch (Exception ex)
            {
                logger.Error("Error in DeliveryDayController AddDayCode" + ex.Message);
             //   Response.Write("<script>alert('Day Code Exists!!!');</script>");
             //   throw ex;
                SLEWebPortal.Models.DelieveryViewModel model2 = new Models.DelieveryViewModel();
                model2.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();
                model2.TotalCodesForToday = new Managers.DayCodeManager().GetDayCodeListForToday();
                //model2.TotalDevices = model2.Devices.Count;
                //model2.ActiveDevices = Convert.ToInt32(model2.Devices.Count(dev => dev.Active == 1));
                TempData["Weeks"] = mod.Weeks;
                TempData["daycode"] = mod.DelieveryCode;
                TempData["desc"] = mod.Description.Trim();
                return View("Index", model2);

                //var response = new Response(true, "Day Code Exists!");
                //return Json(response);

            }
        }

        public JsonResult check(string deliverycode)
        {
            SLEWebPortal.Models.DelieveryViewModel model1 = new Models.DelieveryViewModel();
            model1.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();
            var code = model1.TotalCodes.Find(i => i.DelieveryCode.ToUpper() == deliverycode.ToUpper());
            if (code == null)
            {
                var response = new Response(true, "Y");
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var response = new Response(true, "N");
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Configuration2( DelieveryViewModel model)
        {
            model.stopsandweeks = new Managers.DayCodeManager().GetConfiguration(model.DelieveryCode);
            return View("Configuration2",model);
        }
        public ActionResult RenderView()
        {
            SLEWebPortal.Models.DelieveryViewModel model = new Models.DelieveryViewModel();
            model.TotalCodes = new Managers.DayCodeManager().GetAllMessages();
            model.TotalCodesForToday = new Managers.DayCodeManager().GetDayCodeListForToday();
            return PartialView("codes",model);
        }

        [HttpPost]
        public ActionResult AddConfig(string[] array,string Code,string Description,string Weeks)
        {
            try
            {

                logger.Info("DeliveryDayController AddConfig Parameters: " + array+","+Code+","+Description+","+Weeks);
                //if (!ModelState.IsValid)
                //{
                //    SLEWebPortal.Models.DelieveryViewModel model = new Models.DelieveryViewModel();
                //    model.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();
                
                //    return View("Index", model);
                //}

                //var daycode = mod.DelieveryCode;
                //var weeks = mod.Weeks;
                //var desc = mod.Description;

              //  bool check = new Managers.DayCodeManager().RemoveConfig(Code);

             //   bool check = new Managers.DayCodeManager().RemoveConfig(Code);
                bool check = new Managers.DayCodeManager().checkifexists(Code);
                if (check == true)
                {
                    for (int i = 0; i < array.Length; i++)
                    {
                        int weekno = Convert.ToInt32(array[i].Substring(0, (array[i].IndexOf('-'))));
                        int dayno = Convert.ToInt32(array[i].Substring((array[i].IndexOf('-') + 1), 1));
                        new Managers.DayCodeManager().AddConfig(Code, weekno, dayno, Description);

                    }

                    new Managers.DayCodeManager().UpdateStatus(Code, Convert.ToInt16(Weeks));
                }
                else {
                    int value = 1 / int.Parse("0");
                }
                //  SLEWebPortal.Models.DelieveryViewModel model2 = new Models.DelieveryViewModel();
                // model2.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();
                //model2.TotalDevices = model2.Devices.Count;
                //model2.ActiveDevices = Convert.ToInt32(model2.Devices.Count(dev => dev.Active == 1));
               // TempData["Weeks"] = mod.Weeks;
          
                return RedirectToAction("Configuration");
            }
            catch (Exception ex)
            {
                logger.Error("Error in DeliveryDayController AddConfig" + ex.Message);
                throw ex;
            }
        }

        public static class JavaScript
        {
            public static string Serialize(object o)
            {
                JavaScriptSerializer js = new JavaScriptSerializer();
                return js.Serialize(o);
            }
        }
        [HttpPost]
   //     public ActionResult EditConfig(string Code, int Stops, int Weeks,string Description)
        public ActionResult EditConfig(DelieveryViewModel mod)
        {
            try
            {
                logger.Info("DeliveryDayController EditConfig Parameters: " + mod );
                var Code = Request["editdaycode2"].ToString();
          //      var Stops =Convert.ToInt16(Request["weekspercycle"].ToString());
           //     var Weeks =Convert.ToInt16(Request["weekspercycle"].ToString());

                var Stops = Convert.ToInt16(Request["stopspercycle"].ToString());
                var Weeks = mod.Weeks;
                if (Convert.ToInt16(Weeks) > 53)
                {
                    ModelState.AddModelError("", "Can Not Update");
                    return View("index");
                }
                else
                { 
                var Description = Request["editdesc2"].ToString();
             //   logger.Info("DeliveryDayController EditConfig Parameters: " + mod);
                //if (!ModelState.IsValid)
                //{
                //    SLEWebPortal.Models.DelieveryViewModel model = new Models.DelieveryViewModel();
                //    model.TotalCodes = new Managers.DayCodeManager().GetDayCodeList();

                //    return View("Index", model);
                //}

                //var daycode = mod.DelieveryCode;
                //var weeks = mod.Weeks;
                //var desc = mod.Description;
              //  new Managers.DayCodeManager().RemoveDayCode(Code);
           //     new Managers.DayCodeManager().RemoveConfig(Code);
              //  new Managers.DayCodeManager().AddDayCode(Code, Weeks, Description);


                  SLEWebPortal.Models.DelieveryViewModel model2 = new Models.DelieveryViewModel();

WebPortal/SLEWebPortal/Views/DeliveryDay/Configuration.cshtml
@{
    ViewBag.Title = "Delivery Day Configuration";
}

@*<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10" style="width:100%;">
        <table style="width:100%;">
            <tr>
                <td style=" width:50%;">
                    <h2>Delivery Day Configuration</h2>
                </td>
                <td style=" width:50%;">
                    <span style="float:right; margin-top:-1%;">@DateTime.Now.ToLongDateString()</span>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-lg-2">

    </div>
</div>*@

@model  SLEWebPortal.Models.DelieveryViewModel

@{int number = Model.Weeks; string Code = Model.DelieveryCode; string Desc = Model.Description;  string[] dayweeks = (string[])TempData["dayweeks"];}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <h4 style=" margin-left:10px;padding: 7px;"><i class="fa fa-calendar-o" style="color:rgb(0, 158, 255);"></i> @Model.DelieveryCode : @Model.Description</h4>
                    <div style="width:35%; float:right; margin-top:-45px;">

                        @*<i class="fa fa-chevron-up"></i>*@
                        <span class="btn btn-primary" style="height:22px;padding:0px; width:7%; border-radius:0px; margin-right:5px;"><span id="totalstops">0</span></span>
                        Stops


                        @*<i class="fa fa-wrench"></i>*@
                        <span class="btn btn-primary" style="height:22px;padding:0px; width:7%;border-radius:0px; text-align:center; margin-left:10px;margin-right:5px;"><span>@number</span></span>
                        Weeks per Cycle

                        <button class="btn btn-sm btn-white " id="resetbutton" type="submit" disabled style="margin-left:10px;">Reset</button>
                        <button class="btn btn-sm btn-white " id="savebutton" type="submit" disabled>Save</button>
                    </div>

                    <table class="table table-bordered" style="border-collapse:collapse;border-spacing: 0;  border-bottom:2px solid #B5B4B4; border-top:2px solid #B5B4B4" cellspacing="0">
                        <tbody>


                            @{int counter = 1; int limitrow = 0; int limitcolumn = 0;}
                            @if (number >= 4)
        {
            limitrow = ((number % 4) == 0) ? ((number / 4) - 1) : number / 4;
            limitcolumn = 4;
                            <tr>
                                @for (int k = 0; k < 4; k++)
                {


            <td style="border-collapse:collapse; border-left:2px solid #B5B4B4;color:rgb(0, 168, 255);text-align:center; width:50px;"><div>Mon</div></td>
            <td style="color:rgb(0, 168, 255);text-align:center;width:50px;"><div>Tue</div></td>
            <td style="color:rgb(0, 168, 255); text-align:center;width:50px;"><div>Wed</div></td>
            <td style="color:rgb(0, 168, 255);text-align:center;width:51px;"><div>Thu</div></td>
            <td style="border-collapse:collapse;border-spacing: 0;border-right:2px solid #B5B4B4;color:rgb(0, 168, 255);text-align:center;width:51px;"><div>Fri</div></td>


                }
                            </tr>
        }
        else
        {
            limitrow = 0;
            limitcolumn = number;
                            <tr>
                                @for (int k = 0; k < limitcolumn; k++)
                {


            <td style="border-collapse:collapse;border-spacing: 0;border-left:2px solid #B5B4B4;color:rgb(0, 168, 255);">Mon</td>
            <td style="color:rgb(0, 168, 255);">Tue</td>
            <td style="color:rgb(0, 168, 255);">Wed</td>
            <td style="color:rgb(0, 168, 255);">Thu</td>
            <td style="border-collapse:collapse;border-spacing: 0;border-right:2px solid #B5B4B4;color:rgb(0, 168, 255);">Fri</td>


                }
                            </tr>
        }
                            @for (int j = 0; j <= limitrow; j++)
        {
            if (j == limitrow && j>0)
            {
                limitcolumn = ((number % 4) == 0) ? 4 : number % 4;
            }

                            <tr style="border-collapse:collapse;border-spacing: 0;border-right:2px solid #B5B4B4;border-left:2px solid #B5B4B4;">
                                @for (int i = 1; i <= limitcolumn; i++)
                {

            <td colspan="5" style="padding:0px; margin-bottom:0px;border-collapse:collapse;border-spacing: 0;border-right:2px solid #B5B4B4;">
                <table class="table table-bordered child" style="margin-bottom:0px;  border-collapse:collapse;border-spacing: 0;" cellspacing="0" cellpadding="0" id="table">

                    <tr>

                        <th colspan="5" align="center" style="text-align:center; background-color:#EBEBEB; border-top:1px solid Gray; padding:5px; color:rgba(128, 128, 128, 0.83)">Week @(counter++)</th>



                    </tr>
                    <tr>
                        <td style="border-collapse:collapse;border-spacing: 0;" class="clickable" id='@(counter-1)-1'></td>
                        <td style="border-collapse:collapse;border-spacing: 0;" class="clickable" id='@(counter-1)-2'></td>
                        <td style="border-collapse:collapse;border-spacing: 0;" class="clickable" id='@(counter-1)-3'></td>
                        <td style="border-collapse:collapse;border-spacing: 0;" class="clickable" id='@(counter-1)-4'></td>
                        <td style="border-collapse:collapse;border-spacing: 0;" class="clickable" id='@(counter-1)-5'></td>
                    </tr>

                </table>
            </td>


                }
                            </tr>
        }
                        </tbody>
                    </table>




                </div>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    @*$(document).ready(function () {
        var arr=[];
        var ct = 0;
        var trs = 0;
        for(count=0;count<@number;count++)
        {
           @{string s;}
            @foreach (string item in dayweeks)
            {

                s=item;
            }

         //   var newarray=[];
            //      var jsarray=
            //
          @*var newarray=  JSON.parse((@dayweeks).replace(/&quot;/g,'"'));
            var jsarray=(@dayweeks).replace(/&quot;/g, '\\"');
            jsarray=jsarray.replace(/&quot;/g, '\\"');

            var t = document.getElementsByClassName("table table-bordered child")[count], // This have to be the ID of your table, not the tag
     d = t.getElementsByTagName("tr"),
     r = 0;

            for (k = 1; k < d.length; k++)
            {
                trs = t.getElementsByTagName("tr")[k];
                r = trs.getElementsByTagName("td");
                for(j=0;j<r.length;j++)
                {
                    if (r[j].className == (@s))
                    {
                        // alert(r[j].id)
                        arr[ct] = r[j].id;
                        ct++;
                    }


                }
            }

        }
        //    alert(arr[0]);



    });*@
    $(function () {
        var counter=0;
        $(document.getElementsByClassName("clickable")).click(function () {

            if(this.className == "clickable")
            {
                document.getElementById("resetbutton").disabled=false;
                document.getElementById("savebutton").disabled=false;
                counter++;
                document.getElementById("totalstops").innerHTML=counter;
            }
            else
            {

                counter--;
                if(counter==0)
                {
                    document.getElementById("resetbutton").disabled=true;
                    document.getElementById("savebutton").disabled=true;
                }
                document.getElementById("totalstops").innerHTML=counter;
            }
            $(this).toggleClass("red-cell");
        });

        $(document.getElementById("resetbutton")).click(function () {
            $(document.getElementsByClassName("clickable")).removeClass("red-cell");
            document.getElementById("resetbutton").disabled=true;
            document.getElementById("savebutton").disabled=true;
            document.getElementById("totalstops").innerHTML=0;
            counter=0;
        });
        $(document.getElementById("savebutton")).click(function () {

            var arr=[];
            var ct = 0;
            var trs = 0;




            for(count=0;count<@number;count++)
            {


                var t = document.getElementsByClassName("table table-bordered child")[count], // This have to be the ID of your table, not the tag
         d = t.getElementsByTagName("tr"),
         r = 0;

                for (k = 1; k < d.length; k++)
                {
                    trs = t.getElementsByTagName("tr")[k];
                    r = trs.getElementsByTagName("td");
                    for(j=0;j<r.length;j++)
                    {
                        if (r[j].className =="clickable red-cell")
                        {
                            //  alert(r[j].id)
                            arr[ct] = r[j].id;
                            ct++;
                        }


                    }
                }

            }
            //    alert(arr[0]);
            $.ajax({
                url: "/DeliveryDay/AddConfig",
                type: "POST",
                contentType: 'application/json',
                data: JSON.stringify({ array: arr,Code:'@Code',Description:'@Desc',Weeks:'@number' }),
                success: function () {
                    alert("Day Codes added successfully");
                    window.location.href='Index';
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    //         alert(xhr.responseText);
                    alert("Configuration Error or Day code already exists!!!");
                    window.location.href='Index';
                  //  alert(thrownError);
                }
            });

        });
    });
</script>

<style type="text/css">
    td {
        background: white;
        padding: 2px;
    }

    .clickable {
        cursor: pointer;
        height: 50px;
    }

    td.red-cell {
        background: #5d9cec; /* Or some other color */
    }
</style>

WebPortal/SLEWebPortal/Views/DeliveryDay/codes.cshtml
@model  SLEWebPortal.Models.DelieveryViewModel


<table class="table" id="maintable">
    <thead>
        <tr>

            <th style="width:15%;text-align:center;">Delivery Code <i class="fa fa-filter"></i></th>
            <th id="escapedesc" style="width:45%;">Description</th>
            <th style="width:15%; text-align:center;">Stops per Cycle <i class="fa fa-filter"></i></th>
            <th style="width:15%; text-align:center;">Weeks per cycle <i class="fa fa-filter"></i></th>

            <th id="escape2" style="width:15%;text-align:center;">Status</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < @Model.TotalCodes.Count; i++)
        {
            if (Model.TotalCodes[i].Status == true)
            {

                <tr onclick="location.href = '@(Url.Action("Configuration2", Model.TotalCodes[i]))'" style=" cursor:pointer;">

                    <td style="width:15%;text-align:center;">@Model.TotalCodes[i].DelieveryCode</td>
                    <td style="width:45%;">@Model.TotalCodes[i].Description.Trim()</td>
                    <td style="width:15%; text-align:center;">@Model.TotalCodes[i].Stops</td>
                    <td style="width:15%;text-align:center;">@Model.TotalCodes[i].Weeks</td>

                    <td style="width:15%;text-align:center;">
                        @if (@Model.TotalCodes[i].Status == false)
                        {
                            @*@Html.ActionLink("Yes ", "ViewLyubomir", "DeliveryDay", null, new { @class = "modal-link btn btn-success" })*@
                            <button id="newbutton" type="button" class="btn btn-primary" style="padding:0px;width:80%; background-color:rgba(14, 15, 14, 0.52); border-color:rgba(26, 179, 148, 0); font-size:small;" data-toggle="modal" data-code="@Model.TotalCodes[i].DelieveryCode" data-weeks="@Model.TotalCodes[i].Weeks" data-description="@Model.TotalCodes[i].Description" data-stops="@Model.TotalCodes[i].Stops" data-target="#myModal7">
                                New
                            </button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-primary" style="padding:0px;width:80%; background-color:rgba(20, 163, 17, 0.68);border-color:rgba(26, 179, 148, 0); font-size:small;">
                                Active
                            </button>
                        }

                        @*<span class="label label-primary">Yes</span>*@

                    </td>
                </tr>
            }
            else
            {
                <tr style="cursor:pointer;" data-toggle="modal" data-code="@Model.TotalCodes[i].DelieveryCode" data-weeks="@Model.TotalCodes[i].Weeks" data-description="@Model.TotalCodes[i].Description" data-stops="@Model.TotalCodes[i].Stops" data-target="#myModal7" data-backdrop="static" onclick="fetchvalues('@Model.TotalCodes[i].DelieveryCode','@Model.TotalCodes[i].Description','@Model.TotalCodes[i].Stops','@Model.TotalCodes[i].Weeks')">

                    <td style="width:15%;text-align:center;">@Model.TotalCodes[i].DelieveryCode</td>
                    <td style="width:45%;">@Model.TotalCodes[i].Description.Trim()</td>
                    <td style="width:15%; text-align:center;">@Model.TotalCodes[i].Stops</td>
                    <td style="width:15%;text-align:center;">@Model.TotalCodes[i].Weeks</td>

                    <td style="width:15%;text-align:center;">
                        @if (@Model.TotalCodes[i].Status == false)
                        {
                            @*@Html.ActionLink("Yes ", "ViewLyubomir", "DeliveryDay", null, new { @class = "modal-link btn btn-success" })*@
                            <button id="newbutton" type="button" class="btn btn-primary" style="padding:0px;width:80%; background-color:rgba(14, 15, 14, 0.52); border-color:rgba(26, 179, 148, 0); font-size:small;">
                                New
                            </button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-primary" style="padding:0px;width:80%; background-color:rgba(20, 163, 17, 0.68);border-color:rgba(26, 179, 148, 0); font-size:small;">
                                Active
                            </button>
                        }

                        @*<span class="label label-primary">Yes</span>*@

                    </td>
                </tr>
            }

        }
    </tbody>
</table>

WebPortal/SLEWebPortal/Views/DeliveryDay/config.cshtml
@{
    ViewBag.Title = "configuration";
}

<h2>configuration</h2>

<div class="ibox-content">


    <table class="table table-bordered">
        <tbody>
            <tr>
                <th>#</th>
                <td colspan="5" align="center">Week 1</td>
                <td colspan="5" align="center">Week 2</td>


            </tr>
            <tr>
                <th>#</th>
                <td>Mon</td>
                <td>Tue</td>
                <td>Wed</td>
                <td>Thu</td>
                <td>Fri</td>
                <td>Mon</td>
                <td>Tue</td>
                <td>Wed</td>
                <td>Thu</td>
                <td>Fri</td>
            </tr>


            <tr>
                <td>1</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>1</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>1</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>




</div>

<script type="text/javascript">

    $(function () {
        $('td').click(function () {
            $(this).toggleClass("red-cell");
        });
    });
</script>

<style type="text/css">
    td {
        background: white;
        cursor: pointer;
        padding: 2px;
    }

        td.red-cell {
            background: Blue; /* Or some other color */
        }
</style>