WebPortal/SLEWebPortal/Models/Route.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SLEWebPortal.Models
{
    public class Route
    {
        public string RouteID { get; set; }
        public string Branch { get; set; }
        public string Description { get; set; }
        public int Customers { get; set; }
        public int Devices { get; set; }
        
    }
}

WebPortal/SLEWebPortal/Controllers/RouteController.cs
using SLEWebPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SLEWebPortal.Controllers
{
    [Authorize]
    [SessionExpire]
    public class RouteController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: Route
        public ActionResult Index()
        {
            try {
                logger.Info("RouteController Index");
            RouteModels models = new RouteModels();
            models.Routes = new Managers.RouteManager().GetRouteList();
            return View(models);
                }
            catch(Exception ex)
            {
                logger.Error("Error in RouteController Index" + ex.Message);
                throw ex;
            }
        }
        public ActionResult RouteCustomers(string routeID)
        {
            try{
                logger.Info("RouteController RouteCustomers Parameters: " + routeID);
            CustomerModels model = new CustomerModels();
            model.Customers = new Managers.CustomerManager().GetCustomersForRoute(routeID);
            return View("RouteCustomers", model);
             }
            catch(Exception ex)
            {
                logger.Error("Error in RouteController RouteCustomers" + ex.Message);
                throw ex;
            }
        }
        public ActionResult RouteDevices(string routeID)
        {
            try {
                logger.Info("RouteController RouteDevices Parameters: " + routeID);
            DeviceViewModel model = new DeviceViewModel();
            model.RouteDevices = new Managers.DeviceManager().GetDeviceListForRoute(routeID);
            return View("RouteDevices", model);
            }
            catch (Exception ex)
            {
                logger.Error("Error in RouteController RouteDevices" + ex.Message);
                throw ex;
            }
        }
    }
}

WebPortal/SLEWebPortal/Views/Route/Index.cshtml
@{
    ViewBag.Title = "Routes listing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SLEWebPortal.Models.RouteModels
@*<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Routes listing</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>*@
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Total Routes : @Model.Routes.Count</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Route ID</th>
                                <th>Route Name</th>
                                <th>Branch Name</th>
                                <th>Customers#</th>
                                <th>Devices#</th>
                                <th>Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 1; i <= @Model.Routes.Count; i++)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@Model.Routes.ElementAt(i-1).RouteID</td>
                                    <td>@Model.Routes.ElementAt(i-1).Branch</td>
                                    <td>@Model.Routes.ElementAt(i-1).Description</td>
                                    <td>@Html.ActionLink("View", "RouteCustomers", new { routeID = @Model.Routes.ElementAt(i - 1).RouteID })</td>
                                    <td>
                                    @Html.ActionLink("View", "RouteDevices", new { routeID = @Model.Routes.ElementAt(i - 1).RouteID })</td>
                                    <td><span class="label label-primary">Yes</span></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

WebPortal/SLEWebPortal/Views/Route/RouteCustomers.cshtml
@{
    ViewBag.Title = "Route Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SLEWebPortal.Models.CustomerModels
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
       <br />
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li class="active">
                <strong>Customers</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Total Customers : @Model.Customers.Count</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover customer-listing-table">
                        <thead>
                            <tr>
                                <th width="100px">#</th>
                                <th>Customer ID</th>
                                <th>Customer Name</th>
                                <th>Address</th>
                                <th>Phone #</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < @Model.Customers.Count; i++)
                            {
                                <tr>
                                    <td>@(++i)</td>
                                    <td>@Model.Customers.ElementAt(--i).CustomerNo</td>
                                    <td>@Model.Customers.ElementAt(i).Name</td>
                                    <td>@Model.Customers.ElementAt(i).Address,<br />
                                        @Model.Customers.ElementAt(i).City,<br />
                                        @Model.Customers.ElementAt(i).State                                    
                                    </td>
                                    <td>@Model.Customers.ElementAt(i).Phone</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")

    <script type="text/javascript">
        $(document).ready(function () {
            $('.customer-listing-table').dataTable();
            /* Init DataTables */
            var oTable = $('#editable').dataTable();
            //"tableTools": {
            //    "sSwfPath": "../scripts/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
            //}
        });

    </script>
}

WebPortal/SLEWebPortal/Views/Route/RouteDevices.cshtml
@{
    ViewBag.Title = "Route Devices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SLEWebPortal.Models.DeviceViewModel
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Route Devices</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Route")">Route</a>
            </li>
            <li class="active">
                <strong>Devices</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Total Devices : @Model.RouteDevices.Count</h5>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped table-bordered table-hover customer-listing-table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Device ID</th>
                                <th>Model</th>
                                <th>Manufacturer</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < @Model.RouteDevices.Count; i++)
                            {
                                <tr>
                                    <td>@(i+1)</td>
                                    <td>@Model.RouteDevices.ElementAt(i).DeviceID</td>
                                    <td>@Model.RouteDevices.ElementAt(i).Model</td>
                                    <td>@Model.RouteDevices.ElementAt(i).Manufacturer</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>