WebPortal/SLEWebPortal/Controllers/CycleCountController.cs
using SLEWebPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace SLEWebPortal.Controllers
{
    [SessionExpire]
    public class CycleCountController : Controller
    {
        //[SessionExpire]
        // GET: Approval
            [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Index()
        {
            Cyclemodel ct = new Cyclemodel();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            List<CyclecountModels> cd = cyclecountmnager.GetCycleCountList();
            List<RouteListModels> rd = cyclecountmnager.GetAllRouteList();
            ct.cyclecountmodels = cd.Where(i => i.StatusType.Trim() == "WKLY").ToList();
            ct.physicalcyclecountmodels = cd.Where(i => i.StatusType.Trim() == "PHYSCL").ToList();
            ct.routelistmodels = rd.Where(i => i.StatusType.Trim() == "WKLY").ToList();
            ct.physicalroutelistmodels = rd.Where(i => i.StatusType.Trim() == "PHYSCL").ToList();
            ct.UserRoles = new Managers.RouteManager().GetRouteSelectableListNew();
            ct.Reasons = new Managers.RouteManager().GetReasonSelectableListNew();

            ViewBag.tab2 = true;
            return View(ct);
        }
        public void tempreq()
        { }

        [HttpPost]
        public ActionResult IndexWeekly(string selectedValue)
        {
            Cyclemodel ct = new Cyclemodel();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            //  List<CyclecountModels> cd = cyclecountmnager.GetCycleCountListByRoute(selectedValue);
            ct.UserRoles = new Managers.RouteManager().GetRouteSelectableListNew();
            //  List<RouteListModels> rd = cyclecountmnager.GetRouteList(selectedValue);

            ct.cyclecountmodels = cyclecountmnager.GetCycleCountListByRouteWeekly(selectedValue);

            ct.routelistmodels = cyclecountmnager.GetRouteListWeekly(selectedValue);
            return PartialView("_CycleCountView", ct);
            // do whatever you want with `selectedValue`
        }

        public ActionResult IndexPhysical(string selectedValue)
        {
            Cyclemodel ct = new Cyclemodel();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            //  List<CyclecountModels> cd = cyclecountmnager.GetCycleCountListByRoute(selectedValue);
            ct.UserRoles = new Managers.RouteManager().GetRouteSelectableListNew();
            //  List<RouteListModels> rd = cyclecountmnager.GetRouteList(selectedValue);

            ct.physicalcyclecountmodels = cyclecountmnager.GetCycleCountListByRoutePhysical(selectedValue);

            ct.physicalroutelistmodels = cyclecountmnager.GetRouteListPhysical(selectedValue);
            return PartialView("_PhysicalCycleCountView", ct);
            // do whatever you want with `selectedValue`
        }
        public ActionResult ShowDetails(int id, string routename)
        {
            CyclecountdetailsModels ccd = new CyclecountdetailsModels();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            //      ccd = cyclecountmnager.GetAllWeeklyCountItemsList(id);
            //     ccd.cyclecountmodels = cyclecountmnager.GetCycleCountListByCountID(id);

            //    ccd.routelistmodels = cyclecountmnager.GetRouteList(routename);
            return View("WeeklyCountRequest", ccd);
            // do whatever you want with `selectedValue`
        }
        public ActionResult WeeklyCountRequest(Cyclemodel model)
        {
            AddCycleCountModel addccd = new AddCycleCountModel();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();

            if (model.SelectedUser.Trim() == "All" || model.SelectedUser == "")
            {
                addccd = cyclecountmnager.GetUserDetails();
                addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsListAll();
            }
            else
            {

                int id = Convert.ToInt16(model.SelectedUser);
                addccd = cyclecountmnager.GetUserDetails(id);
                addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsList(id);
            }


            return View("WeeklyCountRequest", addccd);
        }

        public ActionResult WeeklyCountRequestPhysical(Cyclemodel model)
        {
            AddCycleCountModel addccd = new AddCycleCountModel();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();

            if (model.SelectedUser.Trim() == "All" || model.SelectedUser == "")
            {
                addccd = cyclecountmnager.GetUserDetails();
                addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsListAll();
            }
            else
            {
                int id = Convert.ToInt16(model.SelectedUser);
                addccd = cyclecountmnager.GetUserDetails(id);
                addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsList(id);
            }


            return View("WeeklyCountRequestPhysical", addccd);
        }
        [ValidateInput(false)]
        public ActionResult WeeklyCountRequest2(string countid)
        {
            // int i = 0;
            string selectedValue = countid;
            AddCycleCountModel addccd = new AddCycleCountModel();
            List<CyclecountdetailsModels> ccd2 = new List<CyclecountdetailsModels>();
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            int id = Convert.ToInt16(selectedValue);
            addccd = cyclecountmnager.GetRecountDetails(id);
            addccd.Reasons = new Managers.RouteManager().GetReasonSelectableListNew();
            if (addccd.Status.Trim() == "NEW")
            {
                addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsList(Convert.ToInt16(addccd.RouteID));
            }
            if (addccd.Status.Trim() == "SUBMIT" || addccd.Status.Trim()=="ACCEPT")
            {
                ccd2 = cyclecountmnager.GetWeeklyCountItemsListByCountForSubmit(id);
            }
            else
            {
                ccd2 = cyclecountmnager.GetWeeklyCountItemsListByCount(id);
            }

            ////addccd.ccd =
            ////         (from c in addccd.ccd
            ////         where !(from o in ccd2
            ////                 select o.ItemId)
            ////                .Contains(c.ItemId)
            ////         select c).ToList();
            ViewData["Items"] = ccd2;
            return View("WeeklyCountRequest", addccd);
        }
        //public ActionResult Additems(string[] selected)
        //{
        //    AddCycleCountModel addccd = new AddCycleCountModel();
        //      Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
        //      addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsListMultiple(selected);
        //      Session["Models"] = addccd.ccd;
        //      return PartialView("_NewCountRequest",addccd.ccd);
        //}
        //public ActionResult Deleteitems(decimal[] selected)
        //{

        //    List<CyclecountdetailsModels> cd = new List<CyclecountdetailsModels>();
        //    cd = (List<CyclecountdetailsModels>)Session["Models"];
        //    foreach (decimal s in selected)
        //    { 
        //       CyclecountdetailsModels removeitem=cd.Where(i=>i.ItemId==s).FirstOrDefault();
        //       cd.Remove(removeitem);

        //    }
        //    Session["Models"] = cd;
        //    return PartialView("_NewCountRequest", cd);
        //}

        public string SaveItems(string[] itemids, string routeid, string cycleCountDate)
        {
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            AddCycleCountModel addccd = new AddCycleCountModel();
            addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsListMultiple(itemids);
            addccd.CycleCountDatetime = Convert.ToDateTime(cycleCountDate, new System.Globalization.CultureInfo("en-US", true));
            if (Convert.ToInt16(routeid) == 0)
            {

                addccd.RouteID = Convert.ToDecimal(routeid);
                cyclecountmnager.AddNewWeeklyCountHeaderAll(addccd, cycleCountDate);
            }
            else
            {
                Page p = new Page();
                p.ClientScript.RegisterClientScriptBlock(typeof(Page), "alert", addccd.ccd.Count.ToString());
                addccd.RouteID = Convert.ToDecimal(routeid);
                cyclecountmnager.AddNewWeeklyCountHeader(addccd, routeid, cycleCountDate);
            }
            return addccd.ccd.Count.ToString();
            //  ViewBag.tab2 = 1;
            //   cyclecountmnager.AddNewWeeklyCountDetails(addccd);
            //    return View("Index");
        }


        public string NewSaveItems(string[] itemids, string countid, string cycleCountDate)
        {
            Managers.CycleCountManager cyclecountmnager = new Managers.CycleCountManager();
            AddCycleCountModel addccd = new AddCycleCountModel();
            addccd.ccd = cyclecountmnager.GetAllWeeklyCountItemsListMultiple(itemids);
            addccd.CycleCountID = Convert.ToDecimal(countid);
            addccd.CycleCountDatetime = Convert.ToDateTime(cycleCountDate, new System.Globalization.CultureInfo("en-US", true));
            cyclecountmnager.DeleteItemsInDetails(countid);
            cyclecountmnager.UpdateCountDetails(addccd);
            //if (Convert.ToInt16(routeid) == 0)
            //{

            //    cyclecountmnager.AddNewWeeklyCountHeaderAll(addccd, cycleCountDate);
            //}
            //else
            //{

            //    cyclecountmnager.AddNewWeeklyCountHeader(addccd, routeid, cycleCountDate);
            //}

WebPortal/SLEWebPortal/Views/CycleCount/_NewCountRequest.cshtml
@model IEnumerable<SLEWebPortal.Models.CyclecountdetailsModels>

<table class="table" style="text-align:center;">
    <thead style="border: 1px Solid rgba(128, 128, 128, 0.4); text-align:center; background-color: rgba(128, 128, 128, 0.27);">
        <tr>
            <th></th>
            <th style="text-align:center;">Item No.</th>
            <th style="text-align:center;">Item Description</th>
            <th style="text-align:center;">Sales Cat 1</th>
            <th style="text-align:center;">Sales Cat 2</th>
            <th style="text-align:center;">Sales Cat 5</th>
            <th style="text-align:center;">UOM</th>


        </tr>
    </thead>
    <tbody style="border: 1px Solid rgba(128, 128, 128, 0.4);">
        @foreach(var item in Model)
        { 
        <tr>
            <td><div class="checkbox"><label>@Html.CheckBox("itemId2", new { value = item.ItemId, @class = "check2" })</label></div></td>
            <td>@item.ItemNumber</td>
            <td>@item.ItemDescription</td>
            <td>@item.SalesCat1</td>
            <td>@item.SalesCat2</td>
            <td>@item.SalesCat5</td>
            <td>@item.UOM</td>

        </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        var list2 = [];
      
       
    $(".check2").change(function () {
        if (this.checked) {
            document.getElementById("deletebutton").setAttribute("class", "btn btn-sm btn-white")
            list2.push(this.value);
            //   alert(this.value);
        }
        else {
            //   alert("Unchecked");
            var index = list2.indexOf(this.value);
            if (index > -1) {
                list2.splice(index, 1);
            }

        }
    });

    $('#deletebutton').click(function () {

        document.getElementById("totalcounts").textContent = document.getElementById("totalcounts").textContent - list2.length;


      

        list2.forEach(function (e) {
            var tr = $(document.getElementById("tbl").rows.namedItem(e));
            tr.show();

            //var index = list.indexOf(e);
            //if (index > -1) {
            //    list.splice(index, 1);
            //    listofrows.splice(index, 1);
            //}
        });
      
        // now names contains all of the names of checked checkboxes
        // do something with it for excamle post with ajax
        @*$.ajax({
            url: '@Url.Action("Deleteitems", "CycleCount")',
            type: 'POST',
            dataType: 'html',
            contentType: 'application/json',
            data: JSON.stringify({ selected: list2 }),
            success: function (result) {

              //     alert("success");
                $("#partialviewforitems").html(result);
            },
            error: function (result) {
                alert("error!");
            }
        });*@   //end ajax
    });
   
    });
</script>